In [1]:
import numpy as np 
#Andrade Alvarado Alberto Abraham
arr = np.arange (0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
arr_flot = np.random.rand(4,3)#Andrade Alvarado Alberto Abraham
arr_flot

array([[0.9350355 , 0.19970705, 0.95913565],
       [0.02808201, 0.27837172, 0.94805652],
       [0.82812106, 0.13940601, 0.71185812],
       [0.37110147, 0.13585074, 0.71724197]])

In [4]:
arr_ent = np.random.randint(10, size=(2,3))#Andrade Alvarado Alberto Abraham
arr_ent

array([[2, 7, 0],
       [7, 2, 1]])

In [5]:
arr_6 = np.full((3,3),6) #Andrade Alvarado Alberto Abraham
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [10]:
np.append(arr,[12,13,14,51])#Andrade Alvarado Alberto Abraham

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [11]:
np.insert(arr,2, [42,34])#Andrade Alvarado Alberto Abraham

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.delete(arr_ent,1,axis=0)#Andrade Alvarado Alberto Abraham

array([[2, 7, 0]])