In [1]:
import numpy as np #Andrade Alvarado Alberto Abraham

In [2]:
arreglo = np.array([0,1,2,3,4,5])   #Andrade Alvarado Alberto Abraham

In [3]:
arreglo, type(arreglo) #Andrade Alvarado Alberto Abraham

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [4]:
notas = [16,17,14,17,19,15]         #Andrade Alvarado Alberto Abraham

ar_notas = np.array(notas, dtype=float)

In [5]:
ar_notas, type(ar_notas[0])      #Andrade Alvarado Alberto Abraham

(array([16., 17., 14., 17., 19., 15.]), numpy.float64)

In [6]:
ar_notas_todas = np.array(([0,1,2,3,4,5], notas))     #Andrade Alvarado Alberto Abraham
ar_notas_todas

array([[ 0,  1,  2,  3,  4,  5],
       [16, 17, 14, 17, 19, 15]])

In [7]:
print(ar_notas_todas.ndim)     #Andrade Alvarado Alberto Abraham
print(ar_notas.ndim)

2
1


In [8]:
print(ar_notas_todas.shape)       #Andrade Alvarado Alberto Abraham
print(ar_notas.shape)

(2, 6)
(6,)


In [9]:
arr = np.zeros((2,3), dtype=float)      #Andrade Alvarado Alberto Abraham
print (arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
ar2 = np.ones((3,4), dtype=float)     #Andrade Alvarado Alberto Abraham
print (ar2)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
ar4 = np.identity((4), dtype=float)     #Andrade Alvarado Alberto Abraham
print (ar4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
ar5 = np.arange(1,9)        #Andrade Alvarado Alberto Abraham
print (ar5)

[1 2 3 4 5 6 7 8]
