In [1]:
import numpy as np 

arr_ent = np.random.randint(100,size=(3,4))           #Andrade Alvarado Alberto Abraham
arr_ent

array([[12, 35, 33, 11],
       [34, 39, 71, 71],
       [75, 23, 25, 65]])

In [2]:
arr_ent.astype(float) #Andrade Alvarado Alberto Abraham

array([[12., 35., 33., 11.],
       [34., 39., 71., 71.],
       [75., 23., 25., 65.]])

In [3]:
arr_ent             #Andrade Alvarado Alberto Abraham

array([[12, 35, 33, 11],
       [34, 39, 71, 71],
       [75, 23, 25, 65]])

In [4]:
arr_ent.sort()            #Andrade Alvarado Alberto Abraham
arr_ent

array([[11, 12, 33, 35],
       [34, 39, 71, 71],
       [23, 25, 65, 75]])

In [5]:
arr_ent.sort(axis=0)            #Andrade Alvarado Alberto Abraham
arr_ent

array([[11, 12, 33, 35],
       [23, 25, 65, 71],
       [34, 39, 71, 75]])

In [6]:
arr_ent              #Andrade Alvarado Alberto Abraham

array([[11, 12, 33, 35],
       [23, 25, 65, 71],
       [34, 39, 71, 75]])

In [12]:
arr_ent = arr_ent.reshape(4,3) #Andrade Alvarado Alberto Abraham
arr_ent

array([[11, 12, 33],
       [35, 23, 25],
       [65, 71, 34],
       [39, 71, 75]])

In [13]:
plano_arr = arr_ent.flatten()               #Andrade Alvarado Alberto Abraham

print(arr_ent)
print(plano_arr)

[[11 12 33]
 [35 23 25]
 [65 71 34]
 [39 71 75]]
[11 12 33 35 23 25 65 71 34 39 71 75]


In [14]:
lista_arr = plano_arr.tolist()             #Andrade Alvarado Alberto Abraham
lista_arr

[11, 12, 33, 35, 23, 25, 65, 71, 34, 39, 71, 75]

In [15]:
arrays= np.split(arr_ent,4)             #Andrade Alvarado Alberto Abraham
arrays

[array([[11, 12, 33]]),
 array([[35, 23, 25]]),
 array([[65, 71, 34]]),
 array([[39, 71, 75]])]

In [16]:
np.concatenate((arrays[1],arrays[0]),axis=0)

array([[35, 23, 25],
       [11, 12, 33]])

In [17]:
arr_ent

array([[11, 12, 33],
       [35, 23, 25],
       [65, 71, 34],
       [39, 71, 75]])

In [18]:
t_arr = arr_ent.T
t_arr

array([[11, 35, 65, 39],
       [12, 23, 71, 71],
       [33, 25, 34, 75]])